language: node_js
# nodejs版本
node_js: 
    - '16'

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install
  - gitbook install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
